// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ7av9eUBW148vfv8FdH_TX3hYqhkMZBg',
    appId: '1:383124171119:web:ea4a7544f64b9650c5609a',
    messagingSenderId: '383124171119',
    projectId: 'resqpin',
    authDomain: 'resqpin.firebaseapp.com',
    storageBucket: 'resqpin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTSC-XWKPaYvfD1tBgq5oVEgqxnuia2jE',
    appId: '1:383124171119:android:900c01cf2a2b7d8ec5609a',
    messagingSenderId: '383124171119',
    projectId: 'resqpin',
    storageBucket: 'resqpin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAliKkI96VjyiT8x49i3dw7Vzwm_kjCYZw',
    appId: '1:383124171119:ios:a615a6feedb1ca45c5609a',
    messagingSenderId: '383124171119',
    projectId: 'resqpin',
    storageBucket: 'resqpin.firebasestorage.app',
    iosBundleId: 'com.example.resqpin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAliKkI96VjyiT8x49i3dw7Vzwm_kjCYZw',
    appId: '1:383124171119:ios:a615a6feedb1ca45c5609a',
    messagingSenderId: '383124171119',
    projectId: 'resqpin',
    storageBucket: 'resqpin.firebasestorage.app',
    iosBundleId: 'com.example.resqpin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ7av9eUBW148vfv8FdH_TX3hYqhkMZBg',
    appId: '1:383124171119:web:0c7ac139b1771675c5609a',
    messagingSenderId: '383124171119',
    projectId: 'resqpin',
    authDomain: 'resqpin.firebaseapp.com',
    storageBucket: 'resqpin.firebasestorage.app',
  );
}
